name: "build"

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - env-alpine
          - env-archlinux
          - env-debian:bookworm
          - env-debian:trixie
          - env-debian:latest
          - env-fedora
          - env-opensuse
          - env-ubuntu:22.04
          - env-ubuntu:24.04
          - env-ubuntu:26.04
          - env-ubuntu:latest

    name: linux/${{ matrix.image }}

    env:
      CACHE_FROM: /tmp/dockercache
      CACHE_TO: /tmp/dockercache-new

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CACHE_FROM }}
          key: ${{ runner.os }}-${{ matrix.image }}

      - name: Setup buildx
        run: |
          docker buildx create --use

      - name: Detect env
        if: |
          github.repository_owner == 'tarabah' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        run: |
          echo "ENABLE_PUSH=1" >> $GITHUB_ENV

      - name: Run docker
        run: |
          set -x
          if [[ $ENABLE_PUSH = 1 ]]; then \
            echo "${{ secrets.DOCKER_PASSWORD }}" \
              | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin
            ./make.py --push \
              --cache-from=${{ env.CACHE_FROM }} --cache-to=${{ env.CACHE_TO }} \
              ${{ matrix.image }}
          else
            ./make.py \
              --cache-from=${{ env.CACHE_FROM }} --cache-to=${{ env.CACHE_TO }} \
              ${{ matrix.image }}
          fi

      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ env.CACHE_TO }}
          key: ${{ runner.os }}-${{ matrix.image }}-${{ github.sha }}

  rpios-trixie:
    runs-on: ubuntu-latest

    name: linux/env-rpios-trixie

    env:
      CACHE_FROM: /tmp/dockercache
      CACHE_TO: /tmp/dockercache-new

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        run: |
          docker buildx create --use

      - name: Detect env
        if: |
          github.repository_owner == 'tarabah' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        run: |
          echo "ENABLE_PUSH=1" >> $GITHUB_ENV

      - name: Build env-rpios-trixie
        run: |
          set -x
          if [[ $ENABLE_PUSH = 1 ]]; then \
            echo "${{ secrets.DOCKER_PASSWORD }}" \
              | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin
            ./make.py --push \
              --platform=linux/arm64 \
              --allow=security.insecure \
              env-rpios-trixie
          else
            ./make.py \
              --platform=linux/arm64 \
              --allow=security.insecure \
              env-rpios-trixie
          fi
